### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by allthingssecurity** [declare-lab/flan-alpaca#4]
During inference or upload I get this RuntimeError: Trying to resize storage that is not resizable

I have done training using use_fsdp on 4x RTX A4000 . It ran for 8 hrs on clean alpaca dataset and gave this error. Seems all work gone waste.

Error occurs at this line

model: LightningModel = LightningModel.load_from_checkpoint(path)

And leads to torch utils

**Comment by chiayewken** [comment]
Hi, sorry about this bug, I also just discovered it while training the XXL model, because pytorch-lightning doesn't save the full state dict by default. This may be expected because FSDP is still an experimental feature in pytorch-lightning. I've just pushed the commits to save the full state dict, and FSDP checkpoints works for me now. Hope this fixes the issue for you!
